### ISSUE TITLE
Issue 2(Showing list of files):

### ISSUE THREAD

**Issue by 007sahil** [CSC-COIN/MAIT-Document-Feature-Identification-_2015-16#2]
Showing list of files which users have uploaded in a table.Whichever files users have uploaded it should be shown in table.

**Comment by gr8shivam** [comment]
The list of uploaded files is shown after the user selects & upload the file(s).

<img width="792" alt="upload list" src="https://cloud.githubusercontent.com/assets/4292333/13931127/de17701e-efc7-11e5-98f3-a713bba75e29.png">
