### ISSUE TITLE
 Issue 6(Folder Creation):

### ISSUE THREAD

**Issue by 007sahil** [CSC-COIN/MAIT-Document-Feature-Identification-_2015-16#6]
Folder should be created programitaclly and the list of files should be stored in that related folder accordingly.

**Comment by gr8shivam** [comment]
The folders of respective category are created on the server. The files are moved to respective folders & an option to download the classified folder in a ZIP format is made available to the user.

<img width="424" alt="folders" src="https://cloud.githubusercontent.com/assets/4292333/13931758/c4475818-efca-11e5-800f-e4c58c1b0aa1.png">

Creation of folders on a user's system can't be achieved as it's out of scope for a web app.
