### ISSUE TITLE
Issue 7(Showing Messages):

### ISSUE THREAD

**Issue by 007sahil** [CSC-COIN/MAIT-Document-Feature-Identification-_2015-16#7]
Message should be shown about the file and where they are store in a message table.

**Comment by gr8shivam** [comment]
The results of classify functionality are shown in a tabular format with the column names as "filename" & "category".

<img width="815" alt="classify results" src="https://cloud.githubusercontent.com/assets/4292333/13931576/fabae064-efc9-11e5-87c3-0b83ac13d682.png">
