### ISSUE TITLE
Issue 8(View Functionality in message table): 

### ISSUE THREAD

**Issue by 007sahil** [CSC-COIN/MAIT-Document-Feature-Identification-_2015-16#8]
For each of the files in message table there should be a view button which allows the user to see where the file is store ie it will open that file location in windows system where the file is stored

**Comment by gr8shivam** [comment]
The view functionality can't be achieved in a web app as the files present on a user's system can't be accessed from a web app. 

What is provided is the download ZIP functionality that provides the user the classified files in their respective folders in a compressed format. A user can simply extract the ZIP to get the classified folder which has all the files under their respective folders.
